# Generated by Django 2.2 on 2019-10-31 13:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubuser',
            name='user',
            field=models.OneToOneField(default='Не указано', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='github_link', to=settings.AUTH_USER_MODEL),
        ),
    ]
