# Generated by Django 2.2 on 2019-11-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191031_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_me',
            field=models.TextField(blank=True, max_length=512, null=True, verbose_name='О себе'),
        ),
    ]
