# Generated by Django 3.0.4 on 2020-03-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='status',
            field=models.CharField(choices=[('public', 'Общий'), ('hidden', 'Скрытый'), ('private', 'Приватный')], default='public', max_length=50, verbose_name='Статус'),
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
